---

- service:
    name: "php{{ php_settings.version }}-fpm"
    state: "{{ php_fpm_settings.service_state }}"
    enabled: "{{ php_fpm_settings.service_enabled }}"
  when: ansible_os_family == 'Debian'
