---

- apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C

- apt_repository:
    repo: ppa:ondrej/php

- package:
    name: "php{{ php_settings.version }}-cli"
    state: "{{ php_settings.package_state }}"
